from app.models.user import (
    User,
    UserRole,
    StudentLevel,
    UserBase,
    UserCreate,
    UserRead,
    OTPToken,
    OTPPurpose,
    TeacherProfile,
    TeacherVerificationRequest,
    TeacherRequestStatus,
    Establishment,
    Department,
)
from app.models.contribution import (
    Contribution,
    ContributionStatus,
    ContributionCreate,
    ContributionRead,
    DocumentVersion,
    DocumentPipelineStatus,
    ContributorRequest,
    ContributorRequestStatus,
)
from app.models.gamification import (
    XPTransaction,
    XPTransactionType,
    Badge,
    UserBadge,
    UserStreak,
)
from app.models.course import Course
from app.models.embedding import DocumentEmbedding
from app.models.rag import RAGSession, Message
from app.models.study_tools import (
    FlashcardDeck,
    Flashcard,
    DifficultyLevel,
    QuizSession,
    Question,
    MindMap,
    Summary,
    SummaryFormat,
    AcademicAssetType,
    AcademicAssetCache,
)
from app.models.annotation import DocumentAnnotation
from app.models.intelligence import (
    UserProfile,
    TopicKnowledge,
    UserMemory,
    LearningInsight,
    LearningSpeed,
    LearningStyle,
)
from app.models.collaboration import (
    ForumPost,
    ForumPostStatus,
    ForumReply,
    ForumVote,
    StudyGroup,
    StudyGroupMember,
    LiveSession,
    LearningPathJob,
    LearningPathJobStatus,
)
from app.models.notification import Notification
from app.models.progress import ReadingProgress


__all__ = [
    "User",
    "UserRole",
    "StudentLevel",
    "UserBase",
    "UserCreate",
    "UserRead",
    "TeacherProfile",
    "TeacherVerificationRequest",
    "TeacherRequestStatus",
    "Establishment",
    "Contribution",
    "ContributionStatus",
    "ContributionCreate",
    "ContributionRead",
    "DocumentVersion",
    "DocumentPipelineStatus",
    "ContributorRequest",
    "ContributorRequestStatus",
    "DocumentEmbedding",
    "XPTransaction",
    "XPTransactionType",
    "Badge",
    "UserBadge",
    "UserStreak",
    "OTPToken",
    "OTPPurpose",
    "Course",
    "Department",
    "RAGSession",
    "Message",
    "FlashcardDeck",
    "Flashcard",
    "DifficultyLevel",
    "QuizSession",
    "Question",
    "MindMap",
    "Summary",
    "SummaryFormat",
    "AcademicAssetType",
    "AcademicAssetCache",
    "DocumentAnnotation",
    "Notification",
    "ReadingProgress",
    # US-XX: User Intelligence Layer
    "UserProfile",
    "TopicKnowledge",
    "UserMemory",
    "LearningInsight",
    "LearningSpeed",
    "LearningStyle",
    "ForumPost",
    "ForumPostStatus",
    "ForumReply",
    "ForumVote",
    "StudyGroup",
    "StudyGroupMember",
    "LiveSession",
    "LearningPathJob",
    "LearningPathJobStatus",
]
