"""add is_deleted to Course

Revision ID: 185935515768
Revises: 9c3b0f2a1d4e
Create Date: 2026-04-07 14:06:45.412934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "185935515768"
down_revision: Union[str, None] = "9c3b0f2a1d4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "course", sa.Column("is_deleted", sa.Boolean(), server_default=sa.false(), nullable=False)
    )
    op.create_index(op.f("ix_course_is_deleted"), "course", ["is_deleted"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_course_is_deleted"), table_name="course")
    op.drop_column("course", "is_deleted")
    # ### end Alembic commands ###
