"""add_domain_manager_flag

Revision ID: 31f866632366
Revises: af53086ec5c1
Create Date: 2026-04-13 17:08:18.082300

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Added to support SQLModel specific types if needed


# revision identifiers, used by Alembic.
revision: str = "31f866632366"
down_revision: Union[str, None] = "af53086ec5c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "establishment",
        sa.Column("is_authorized", sa.Boolean(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "establishment", sa.Column("domain", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_establishment_is_authorized"), table_name="establishment")
    op.create_index(op.f("ix_establishment_domain"), "establishment", ["domain"], unique=True)
    op.drop_column("establishment", "is_authorized")
    # ### end Alembic commands ###
