"""Clean Initial Schema V2 (Squashed)

Revision ID: 3dfb39954c76
Revises: 
Create Date: 2026-03-23 18:21:00.759292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added to support SQLModel specific types if needed
from sqlalchemy.dialects import postgresql

try:
    import pgvector.sqlalchemy
    HAS_PGVECTOR = True
except ModuleNotFoundError:
    HAS_PGVECTOR = False

VECTOR_COLUMN_TYPE = (
    pgvector.sqlalchemy.vector.VECTOR(dim=768) if HAS_PGVECTOR else sa.JSON()
)

# revision identifiers, used by Alembic.
revision: str = '3dfb39954c76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    if HAS_PGVECTOR:
        op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('min_xp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badge_code'), 'badge', ['code'], unique=True)
    op.create_index(op.f('ix_badge_min_xp'), 'badge', ['min_xp'], unique=False)
    
    op.create_table('establishment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_establishment_domain'), 'establishment', ['domain'], unique=True)
    op.create_index(op.f('ix_establishment_name'), 'establishment', ['name'], unique=False)
    
    op.create_table('department',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('establishment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_name'), 'department', ['name'], unique=False)
    
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('establishment_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('filiere', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('level', sa.Enum('L1', 'L2', 'L3', 'M1', 'M2', name='studentlevel'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    
    op.create_table('course',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('level', sa.Enum('L1', 'L2', 'L3', 'M1', 'M2', 'Doctorat', 'OTHER', name='courselevel'), nullable=False),
    sa.Column('course_type', sa.Enum('LECTURE', 'TD', 'TP', 'EXAM', 'SUMMARY', 'OTHER', name='coursetype'), nullable=False),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sa.Enum('FR', 'EN', 'AR', name='courselanguage'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_academic_year'), 'course', ['academic_year'], unique=False)
    op.create_index(op.f('ix_course_course_type'), 'course', ['course_type'], unique=False)
    op.create_index(op.f('ix_course_department_id'), 'course', ['department_id'], unique=False)
    op.create_index(op.f('ix_course_language'), 'course', ['language'], unique=False)
    op.create_index(op.f('ix_course_level'), 'course', ['level'], unique=False)
    op.create_index(op.f('ix_course_title'), 'course', ['title'], unique=False)
    
    op.create_table('otptoken',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('ACCOUNT_ACTIVATION', 'TEACHER_ONBOARDING', 'PASSWORD_RESET', name='otppurpose'), nullable=False),
    sa.Column('otp_code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otptoken_user_id'), 'otptoken', ['user_id'], unique=False)
    
    op.create_table('teacherprofile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('specialization', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('modules', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invite_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_teacherprofile_invite_token'), 'teacherprofile', ['invite_token'], unique=True)
    
    op.create_table('userbadge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('badge_id', sa.Uuid(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badge')
    )
    op.create_index(op.f('ix_userbadge_badge_id'), 'userbadge', ['badge_id'], unique=False)
    op.create_index(op.f('ix_userbadge_user_id'), 'userbadge', ['user_id'], unique=False)
    
    op.create_table('xptransaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('UPLOAD', 'APPROVAL', 'REFERRAL', name='xptransactiontype'), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'transaction_type', 'reference_id', name='uq_xp_transaction_reference')
    )
    op.create_index(op.f('ix_xptransaction_reference_id'), 'xptransaction', ['reference_id'], unique=False)
    op.create_index(op.f('ix_xptransaction_user_id'), 'xptransaction', ['user_id'], unique=False)
    
    op.create_table('contribution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REVISION_REQUESTED', name='contributionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quality_flag', sa.Boolean(), nullable=False),
    sa.Column('uploader_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contribution_course_id'), 'contribution', ['course_id'], unique=False)
    op.create_index(op.f('ix_contribution_created_at'), 'contribution', ['created_at'], unique=False)
    op.create_index(op.f('ix_contribution_quality_flag'), 'contribution', ['quality_flag'], unique=False)
    op.create_index(op.f('ix_contribution_title'), 'contribution', ['title'], unique=False)
    op.create_index(op.f('ix_contribution_uploader_id'), 'contribution', ['uploader_id'], unique=False)
    
    op.create_table('documentversion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ocr_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('simhash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipeline_status', sa.Enum('QUEUED', 'OCR_PROCESSING', 'EMBEDDING', 'READY', 'FAILED', name='documentpipelinestatus'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('contribution_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contribution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentversion_contribution_id'), 'documentversion', ['contribution_id'], unique=False)
    op.create_index(op.f('ix_documentversion_is_deleted'), 'documentversion', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_documentversion_sha256_hash'), 'documentversion', ['sha256_hash'], unique=False)
    op.create_index(op.f('ix_documentversion_simhash'), 'documentversion', ['simhash'], unique=False)
    
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('contribution_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contribution.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)

    op.create_table('readingprogress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('last_page', sa.Integer(), nullable=False),
    sa.Column('scroll_y', sa.Float(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['documentversion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readingprogress_document_version_id'), 'readingprogress', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_readingprogress_user_id'), 'readingprogress', ['user_id'], unique=False)
    
    op.create_table('documentannotation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['documentversion.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentannotation_created_at'), 'documentannotation', ['created_at'], unique=False)
    op.create_index(op.f('ix_documentannotation_document_version_id'), 'documentannotation', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_documentannotation_is_public'), 'documentannotation', ['is_public'], unique=False)
    op.create_index(op.f('ix_documentannotation_page_number'), 'documentannotation', ['page_number'], unique=False)
    op.create_index(op.f('ix_documentannotation_user_id'), 'documentannotation', ['user_id'], unique=False)
    
    op.create_table('documentembedding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('vector', VECTOR_COLUMN_TYPE, nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['documentversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if HAS_PGVECTOR:
        op.create_index('ix_document_embedding_vector_hnsw', 'documentembedding', ['vector'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'vector': 'vector_cosine_ops'})
    op.create_index(op.f('ix_documentembedding_document_version_id'), 'documentembedding', ['document_version_id'], unique=False)
    
    op.create_table('flashcarddeck',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('share_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('card_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['documentversion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcarddeck_document_version_id'), 'flashcarddeck', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_flashcarddeck_share_token'), 'flashcarddeck', ['share_token'], unique=True)
    op.create_index(op.f('ix_flashcarddeck_student_id'), 'flashcarddeck', ['student_id'], unique=False)
    
    op.create_table('mindmap',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_lang', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nodes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('edges_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['documentversion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mindmap_document_version_id'), 'mindmap', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_mindmap_student_id'), 'mindmap', ['student_id'], unique=False)
    op.create_index(op.f('ix_mindmap_target_lang'), 'mindmap', ['target_lang'], unique=False)
    
    op.create_table('quizsession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['documentversion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizsession_created_at'), 'quizsession', ['created_at'], unique=False)
    op.create_index(op.f('ix_quizsession_document_version_id'), 'quizsession', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_quizsession_is_completed'), 'quizsession', ['is_completed'], unique=False)
    op.create_index(op.f('ix_quizsession_student_id'), 'quizsession', ['student_id'], unique=False)
    
    op.create_table('ragsession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['documentversion.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ragsession_document_version_id'), 'ragsession', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_ragsession_student_id'), 'ragsession', ['student_id'], unique=False)
    
    op.create_table('summary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.Enum('EXECUTIVE', 'STRUCTURED', 'COMPARATIVE', name='summaryformat'), nullable=False),
    sa.Column('target_lang', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['documentversion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_document_version_id'), 'summary', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_summary_format'), 'summary', ['format'], unique=False)
    op.create_index(op.f('ix_summary_student_id'), 'summary', ['student_id'], unique=False)
    op.create_index(op.f('ix_summary_target_lang'), 'summary', ['target_lang'], unique=False)
    
    op.create_table('flashcard',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), nullable=False),
    sa.Column('next_review_at', sa.DateTime(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcarddeck.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_deck_id'), 'flashcard', ['deck_id'], unique=False)
    op.create_index(op.f('ix_flashcard_next_review_at'), 'flashcard', ['next_review_at'], unique=False)
    
    op.create_table('message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True), # US-12 Added Field
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('cosine_similarity', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ragsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_session_id'), 'message', ['session_id'], unique=False)
    
    op.create_table('question',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_session_id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('student_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('ai_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_session_id'], ['quizsession.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_is_correct'), 'question', ['is_correct'], unique=False)
    op.create_index(op.f('ix_question_quiz_session_id'), 'question', ['quiz_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_quiz_session_id'), table_name='question')
    op.drop_index(op.f('ix_question_is_correct'), table_name='question')
    op.drop_table('question')
    
    op.drop_index(op.f('ix_message_session_id'), table_name='message')
    op.drop_table('message')
    
    op.drop_index(op.f('ix_flashcard_next_review_at'), table_name='flashcard')
    op.drop_index(op.f('ix_flashcard_deck_id'), table_name='flashcard')
    op.drop_table('flashcard')
    
    op.drop_index(op.f('ix_summary_target_lang'), table_name='summary')
    op.drop_index(op.f('ix_summary_student_id'), table_name='summary')
    op.drop_index(op.f('ix_summary_format'), table_name='summary')
    op.drop_index(op.f('ix_summary_document_version_id'), table_name='summary')
    op.drop_table('summary')
    
    op.drop_index(op.f('ix_ragsession_student_id'), table_name='ragsession')
    op.drop_index(op.f('ix_ragsession_document_version_id'), table_name='ragsession')
    op.drop_table('ragsession')
    
    op.drop_index(op.f('ix_quizsession_student_id'), table_name='quizsession')
    op.drop_index(op.f('ix_quizsession_is_completed'), table_name='quizsession')
    op.drop_index(op.f('ix_quizsession_document_version_id'), table_name='quizsession')
    op.drop_index(op.f('ix_quizsession_created_at'), table_name='quizsession')
    op.drop_table('quizsession')
    
    op.drop_index(op.f('ix_mindmap_target_lang'), table_name='mindmap')
    op.drop_index(op.f('ix_mindmap_student_id'), table_name='mindmap')
    op.drop_index(op.f('ix_mindmap_document_version_id'), table_name='mindmap')
    op.drop_table('mindmap')
    
    op.drop_index(op.f('ix_flashcarddeck_student_id'), table_name='flashcarddeck')
    op.drop_index(op.f('ix_flashcarddeck_share_token'), table_name='flashcarddeck')
    op.drop_index(op.f('ix_flashcarddeck_document_version_id'), table_name='flashcarddeck')
    op.drop_table('flashcarddeck')
    
    op.drop_index(op.f('ix_documentembedding_document_version_id'), table_name='documentembedding')
    if HAS_PGVECTOR:
        op.drop_index('ix_document_embedding_vector_hnsw', table_name='documentembedding', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'vector': 'vector_cosine_ops'})
    op.drop_table('documentembedding')
    
    op.drop_index(op.f('ix_documentannotation_user_id'), table_name='documentannotation')
    op.drop_index(op.f('ix_documentannotation_page_number'), table_name='documentannotation')
    op.drop_index(op.f('ix_documentannotation_is_public'), table_name='documentannotation')
    op.drop_index(op.f('ix_documentannotation_document_version_id'), table_name='documentannotation')
    op.drop_index(op.f('ix_documentannotation_created_at'), table_name='documentannotation')
    op.drop_table('documentannotation')
    
    op.drop_index(op.f('ix_readingprogress_user_id'), table_name='readingprogress')
    op.drop_index(op.f('ix_readingprogress_document_version_id'), table_name='readingprogress')
    op.drop_table('readingprogress')
    
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    
    op.drop_index(op.f('ix_documentversion_simhash'), table_name='documentversion')
    op.drop_index(op.f('ix_documentversion_sha256_hash'), table_name='documentversion')
    op.drop_index(op.f('ix_documentversion_is_deleted'), table_name='documentversion')
    op.drop_index(op.f('ix_documentversion_contribution_id'), table_name='documentversion')
    op.drop_table('documentversion')
    
    op.drop_index(op.f('ix_contribution_uploader_id'), table_name='contribution')
    op.drop_index(op.f('ix_contribution_title'), table_name='contribution')
    op.drop_index(op.f('ix_contribution_quality_flag'), table_name='contribution')
    op.drop_index(op.f('ix_contribution_created_at'), table_name='contribution')
    op.drop_index(op.f('ix_contribution_course_id'), table_name='contribution')
    op.drop_table('contribution')
    
    op.drop_index(op.f('ix_xptransaction_user_id'), table_name='xptransaction')
    op.drop_index(op.f('ix_xptransaction_reference_id'), table_name='xptransaction')
    op.drop_table('xptransaction')
    
    op.drop_index(op.f('ix_userbadge_user_id'), table_name='userbadge')
    op.drop_index(op.f('ix_userbadge_badge_id'), table_name='userbadge')
    op.drop_table('userbadge')
    
    op.drop_index(op.f('ix_teacherprofile_invite_token'), table_name='teacherprofile')
    op.drop_table('teacherprofile')
    
    op.drop_index(op.f('ix_otptoken_user_id'), table_name='otptoken')
    op.drop_table('otptoken')
    
    op.drop_index(op.f('ix_course_title'), table_name='course')
    op.drop_index(op.f('ix_course_level'), table_name='course')
    op.drop_index(op.f('ix_course_language'), table_name='course')
    op.drop_index(op.f('ix_course_department_id'), table_name='course')
    op.drop_index(op.f('ix_course_course_type'), table_name='course')
    op.drop_index(op.f('ix_course_academic_year'), table_name='course')
    op.drop_table('course')
    
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    
    op.drop_index(op.f('ix_department_name'), table_name='department')
    op.drop_table('department')
    
    op.drop_index(op.f('ix_establishment_name'), table_name='establishment')
    op.drop_index(op.f('ix_establishment_domain'), table_name='establishment')
    op.drop_table('establishment')
    
    op.drop_index(op.f('ix_badge_min_xp'), table_name='badge')
    op.drop_index(op.f('ix_badge_code'), table_name='badge')
    op.drop_table('badge')
    
    if HAS_PGVECTOR:
        op.execute('DROP EXTENSION IF EXISTS vector;')
    # ### end Alembic commands ###
