"""Add SOTA Auth Fields

Revision ID: 4700fd57582d
Revises: b5d6a4f3c210
Create Date: 2026-04-02 15:00:59.688985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added to support SQLModel specific types if needed


# revision identifiers, used by Alembic.
revision: str = '4700fd57582d'
down_revision: Union[str, None] = 'b5d6a4f3c210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    accountstatus = sa.Enum('ACTIVE', 'PENDING_VERIFICATION', 'SUSPENDED', name='accountstatus')
    accountstatus.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', accountstatus, server_default='ACTIVE', nullable=False))
    op.add_column('user', sa.Column('trust_score', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('profile_completeness', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_completeness')
    op.drop_column('user', 'trust_score')
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
