"""make contribution uploader_id nullable with set null on delete

Revision ID: 49e3f1fdc870
Revises: cf6fe33b8970
Create Date: 2026-04-22 17:35:10.309224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added to support SQLModel specific types if needed
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49e3f1fdc870'
down_revision: Union[str, None] = 'cf6fe33b8970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contribution', 'course_type',
               existing_type=postgresql.ENUM('LECTURE', 'TD', 'TP', 'EXAM', 'SUMMARY', 'OTHER', name='coursetype'),
               nullable=False)
    op.alter_column('contribution', 'language',
               existing_type=postgresql.ENUM('FR', 'EN', 'AR', name='courselanguage'),
               nullable=False)
    op.alter_column('contribution', 'uploader_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('contribution_uploader_id_fkey'), 'contribution', type_='foreignkey')
    op.create_foreign_key(None, 'contribution', 'user', ['uploader_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_establishment_domain'), table_name='establishment')
    op.create_index(op.f('ix_establishment_domain'), 'establishment', ['domain'], unique=False)
    op.create_index(op.f('ix_establishment_is_authorized'), 'establishment', ['is_authorized'], unique=False)
    op.alter_column('userprofile', 'learning_speed',
               existing_type=postgresql.ENUM('SLOW', 'MEDIUM', 'FAST', name='learningspeed'),
               nullable=False)
    op.alter_column('userprofile', 'preferred_style',
               existing_type=postgresql.ENUM('VISUAL', 'TEXTUAL', 'MIXED', name='learningstyle'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userprofile', 'preferred_style',
               existing_type=postgresql.ENUM('VISUAL', 'TEXTUAL', 'MIXED', name='learningstyle'),
               nullable=True)
    op.alter_column('userprofile', 'learning_speed',
               existing_type=postgresql.ENUM('SLOW', 'MEDIUM', 'FAST', name='learningspeed'),
               nullable=True)
    op.drop_index(op.f('ix_establishment_is_authorized'), table_name='establishment')
    op.drop_index(op.f('ix_establishment_domain'), table_name='establishment')
    op.create_index(op.f('ix_establishment_domain'), 'establishment', ['domain'], unique=True)
    op.drop_constraint(None, 'contribution', type_='foreignkey')
    op.create_foreign_key(op.f('contribution_uploader_id_fkey'), 'contribution', 'user', ['uploader_id'], ['id'])
    op.alter_column('contribution', 'uploader_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('contribution', 'language',
               existing_type=postgresql.ENUM('FR', 'EN', 'AR', name='courselanguage'),
               nullable=True)
    op.alter_column('contribution', 'course_type',
               existing_type=postgresql.ENUM('LECTURE', 'TD', 'TP', 'EXAM', 'SUMMARY', 'OTHER', name='coursetype'),
               nullable=True)
    # ### end Alembic commands ###