"""Add UserStreak model for learning streaks

Revision ID: 7ba4e1182a2b
Revises: 3dfb39954c76
Create Date: 2026-03-30 10:55:53.730189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added to support SQLModel specific types if needed


# revision identifiers, used by Alembic.
revision: str = '7ba4e1182a2b'
down_revision: Union[str, None] = '3dfb39954c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###