"""add_user_settings

Revision ID: a02750f52a1a
Revises: 49e3f1fdc870
Create Date: 2026-04-22 18:55:18.949495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added to support SQLModel specific types if needed


# revision identifiers, used by Alembic.
revision: str = 'a02750f52a1a'
down_revision: Union[str, None] = '49e3f1fdc870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('push_notifications_enabled', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('email_digest_enabled', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('notification_types', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('is_rtl', sa.Boolean(), nullable=True))
    
    # Set defaults for existing rows
    op.execute("UPDATE \"user\" SET push_notifications_enabled = true")
    op.execute("UPDATE \"user\" SET email_digest_enabled = false")
    op.execute("UPDATE \"user\" SET notification_types = '[\"contributions\", \"achievements\", \"reminders\", \"leaderboard\"]'::json")
    op.execute("UPDATE \"user\" SET is_rtl = false")
    
    # Make them non-nullable
    op.alter_column('user', 'push_notifications_enabled', nullable=False)
    op.alter_column('user', 'email_digest_enabled', nullable=False)
    op.alter_column('user', 'notification_types', nullable=False)
    op.alter_column('user', 'is_rtl', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_rtl')
    op.drop_column('user', 'notification_types')
    op.drop_column('user', 'email_digest_enabled')
    op.drop_column('user', 'push_notifications_enabled')
    # ### end Alembic commands ###