"""add_cascade_delete_to_department_courses

Revision ID: fdc6de22aac0
Revises: f6a2d1c7b8e9
Create Date: 2026-04-12 10:27:53.301628

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Added to support SQLModel specific types if needed
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fdc6de22aac0"
down_revision: Union[str, None] = "f6a2d1c7b8e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE forumpoststatus AS ENUM ('OPEN', 'RESOLVED');")
    op.drop_constraint(
        op.f("contributorrequest_demo_contribution_id_key"), "contributorrequest", type_="unique"
    )
    op.drop_index(
        op.f("ix_contributorrequest_demo_contribution_id"), table_name="contributorrequest"
    )
    op.create_index(
        op.f("ix_contributorrequest_demo_contribution_id"),
        "contributorrequest",
        ["demo_contribution_id"],
        unique=True,
    )
    op.drop_constraint(op.f("course_department_id_fkey"), "course", type_="foreignkey")
    op.create_foreign_key(
        None, "course", "department", ["department_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "documentversion",
        sa.Column("parser_used", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "documentversion", sa.Column("has_structured_content", sa.Boolean(), nullable=False)
    )
    op.alter_column(
        "forumpost",
        "content_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    # Manually check and create enum if missing before ALTER TABLE
    op.execute(
        "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'forumpoststatus') THEN CREATE TYPE forumpoststatus AS ENUM ('OPEN', 'RESOLVED'); END IF; END $$;"
    )
    op.alter_column(
        "forumpost",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("OPEN", "RESOLVED", name="forumpoststatus"),
        postgresql_using="status::forumpoststatus",
        existing_nullable=False,
    )
    op.execute(
        "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'learningpathjobstatus') THEN CREATE TYPE learningpathjobstatus AS ENUM ('PROCESSING', 'READY', 'FAILED'); END IF; END $$;"
    )
    op.alter_column(
        "learningpathjob",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("PROCESSING", "READY", "FAILED", name="learningpathjobstatus"),
        postgresql_using="status::learningpathjobstatus",
        existing_nullable=False,
    )

    op.alter_column(
        "forumpost",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("OPEN", "RESOLVED", name="forumpoststatus"),
        postgresql_using="status::forumpoststatus",
        existing_nullable=False,
    )
    op.alter_column(
        "forumreply",
        "content_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "learninginsight",
        "insight_text",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "learninginsight",
        "action_payload",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
    )
    op.drop_index(op.f("ix_learninginsight_insight_type"), table_name="learninginsight")
    op.drop_constraint(op.f("learninginsight_user_id_fkey"), "learninginsight", type_="foreignkey")
    op.create_foreign_key(None, "learninginsight", "user", ["user_id"], ["id"])
    op.alter_column(
        "learningpathjob",
        "input_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "learningpathjob",
        "result_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "learningpathjob",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("PROCESSING", "READY", "FAILED", name="learningpathjobstatus"),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("ragsession_student_id_fkey"), "ragsession", type_="foreignkey")
    op.drop_constraint(
        op.f("ragsession_document_version_id_fkey"), "ragsession", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "ragsession", "documentversion", ["document_version_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "ragsession", "user", ["student_id"], ["id"], ondelete="CASCADE")
    op.alter_column(
        "studygroup",
        "notes_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_constraint(op.f("topicknowledge_user_id_fkey"), "topicknowledge", type_="foreignkey")
    op.drop_constraint(op.f("topicknowledge_course_id_fkey"), "topicknowledge", type_="foreignkey")
    op.create_foreign_key(None, "topicknowledge", "user", ["user_id"], ["id"])
    op.create_foreign_key(None, "topicknowledge", "course", ["course_id"], ["id"])
    op.execute(
        "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gender') THEN CREATE TYPE gender AS ENUM ('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY'); END IF; END $$;"
    )
    op.alter_column(
        "user",
        "gender",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("MALE", "FEMALE", "OTHER", "PREFER_NOT_TO_SAY", name="gender"),
        postgresql_using="gender::gender",
        existing_nullable=True,
    )
    op.alter_column(
        "usermemory",
        "content",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("usermemory_related_course_id_fkey"), "usermemory", type_="foreignkey")
    op.drop_constraint(op.f("usermemory_user_id_fkey"), "usermemory", type_="foreignkey")
    op.execute(
        "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'learningspeed') THEN CREATE TYPE learningspeed AS ENUM ('SLOW', 'MEDIUM', 'FAST'); END IF; END $$;"
    )
    op.execute(
        "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'learningstyle') THEN CREATE TYPE learningstyle AS ENUM ('VISUAL', 'TEXTUAL', 'MIXED'); END IF; END $$;"
    )
    op.create_foreign_key(None, "usermemory", "user", ["user_id"], ["id"])
    op.alter_column(
        "userprofile",
        "learning_speed",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("SLOW", "MEDIUM", "FAST", name="learningspeed"),
        postgresql_using="learning_speed::learningspeed",
        nullable=True,
    )
    op.alter_column(
        "userprofile",
        "preferred_style",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("VISUAL", "TEXTUAL", "MIXED", name="learningstyle"),
        postgresql_using="preferred_style::learningstyle",
        nullable=True,
    )
    op.drop_constraint(op.f("userprofile_user_id_key"), "userprofile", type_="unique")
    op.drop_constraint(op.f("userprofile_user_id_fkey"), "userprofile", type_="foreignkey")
    op.create_foreign_key(None, "userprofile", "user", ["user_id"], ["id"])
    op.add_column("userstreak", sa.Column("freeze_start", sa.DateTime(), nullable=True))
    op.add_column("userstreak", sa.Column("freeze_end", sa.DateTime(), nullable=True))
    op.alter_column(
        "userstreak",
        "last_activity_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_constraint(op.f("userstreak_user_id_key"), "userstreak", type_="unique")
    op.drop_constraint(op.f("userstreak_user_id_fkey"), "userstreak", type_="foreignkey")
    op.create_foreign_key(None, "userstreak", "user", ["user_id"], ["id"])
    op.drop_column("userstreak", "streak_freeze_count")
    op.drop_column("userstreak", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "userstreak",
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "userstreak",
        sa.Column(
            "streak_freeze_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "userstreak", type_="foreignkey")
    op.create_foreign_key(
        op.f("userstreak_user_id_fkey"),
        "userstreak",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        op.f("userstreak_user_id_key"),
        "userstreak",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "userstreak",
        "last_activity_date",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
    )
    op.drop_column("userstreak", "freeze_end")
    op.drop_column("userstreak", "freeze_start")
    op.drop_constraint(None, "userprofile", type_="foreignkey")
    op.create_foreign_key(
        op.f("userprofile_user_id_fkey"),
        "userprofile",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        op.f("userprofile_user_id_key"),
        "userprofile",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "userprofile",
        "preferred_style",
        existing_type=sa.Enum("VISUAL", "TEXTUAL", "MIXED", name="learningstyle"),
        type_=sa.VARCHAR(length=20),
        nullable=True,
    )
    op.alter_column(
        "userprofile",
        "learning_speed",
        existing_type=sa.Enum("SLOW", "MEDIUM", "FAST", name="learningspeed"),
        type_=sa.VARCHAR(length=20),
        nullable=True,
    )
    op.drop_constraint(None, "usermemory", type_="foreignkey")
    op.create_foreign_key(
        op.f("usermemory_user_id_fkey"),
        "usermemory",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("usermemory_related_course_id_fkey"),
        "usermemory",
        "course",
        ["related_course_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "usermemory",
        "content",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "gender",
        existing_type=sa.Enum("MALE", "FEMALE", "OTHER", "PREFER_NOT_TO_SAY", name="gender"),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "topicknowledge", type_="foreignkey")
    op.drop_constraint(None, "topicknowledge", type_="foreignkey")
    op.create_foreign_key(
        op.f("topicknowledge_course_id_fkey"),
        "topicknowledge",
        "course",
        ["course_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("topicknowledge_user_id_fkey"),
        "topicknowledge",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "studygroup",
        "notes_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.drop_constraint(None, "ragsession", type_="foreignkey")
    op.drop_constraint(None, "ragsession", type_="foreignkey")
    op.create_foreign_key(
        op.f("ragsession_document_version_id_fkey"),
        "ragsession",
        "documentversion",
        ["document_version_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("ragsession_student_id_fkey"), "ragsession", "user", ["student_id"], ["id"]
    )
    op.alter_column(
        "learningpathjob",
        "status",
        existing_type=sa.Enum("PROCESSING", "READY", "FAILED", name="learningpathjobstatus"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "learningpathjob",
        "result_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "learningpathjob",
        "input_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.drop_constraint(None, "learninginsight", type_="foreignkey")
    op.create_foreign_key(
        op.f("learninginsight_user_id_fkey"),
        "learninginsight",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_learninginsight_insight_type"), "learninginsight", ["insight_type"], unique=False
    )
    op.alter_column(
        "learninginsight",
        "action_payload",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "learninginsight",
        "insight_text",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "forumreply",
        "content_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "forumpost",
        "status",
        existing_type=sa.Enum("OPEN", "RESOLVED", name="forumpoststatus"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "forumpost",
        "content_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.drop_column("documentversion", "has_structured_content")
    op.drop_column("documentversion", "parser_used")
    op.drop_constraint(None, "course", type_="foreignkey")
    op.create_foreign_key(
        op.f("course_department_id_fkey"), "course", "department", ["department_id"], ["id"]
    )
    op.drop_index(
        op.f("ix_contributorrequest_demo_contribution_id"), table_name="contributorrequest"
    )
    op.create_index(
        op.f("ix_contributorrequest_demo_contribution_id"),
        "contributorrequest",
        ["demo_contribution_id"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("contributorrequest_demo_contribution_id_key"),
        "contributorrequest",
        ["demo_contribution_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
